#spring.datasource.url=jdbc:postgresql://db.wcycutbawsfazovtarud.supabase.co:5432/postgres?sslmode=require
SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres

SPRING_DATASOURCE_USERNAME=postgres.wcycutbawsfazovtarud
spring.datasource.password=211amoydabe

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
