#spring.datasource.url=jdbc:postgresql://db.wcycutbawsfazovtarud.supabase.co:5432/postgres?sslmode=require
#spring.datasource.url=jdbc:postgresql://ep-icy-snow-aohjuiw1.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.url=jdbc:postgresql://ep-icy-snow-aohjuiw1.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&options=endpoint%3Dep-icy-snow-aohjuiw1
#postgresql://neondb_owner:@ep-icy-snow-aohjuiw1.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#SPRING_DATASOURCE_USERNAME=postgres.wcycutbawsfazovtarud
#spring.datasource.password=211amoydabe

spring.datasource.username=neondb_owner
spring.datasource.password=npg_H6WSQEPgCaJ7


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
